#!/usr/bin/env ruby

require File.dirname(__FILE__) + '/../config/environment'

require 'erb'

class WikipediaRegister
  def initialize
    @n = 0
    @source = Source.find_by_name("Wikipedia (ja)")
    if @source.nil?
      @source = Source.create(:name => "Wikipedia (ja)",
                              :description => "Wikipedia in Japanese",
                              :url => "http://ja.wikipedia.org/",
                              :license => "GFDL",
                              :license_url => "http://ja.wikipedia.org/wiki/Wikipedia:Text_of_GNU_Free_Documentation_License")
    end
  end

  def page(information)
    @n += 1
    title = information[:title]
    url = "http://ja.wikipedia.org/wiki/#{ERB::Util.url_encode(title)}"
    p [@n, title]
    user = information[:contributor]
    user = nil unless user.is_a?(User)
    Document.create(:title => information[:title],
                    :content => information[:content],
                    :updated_at => information[:timestamp],
                    :user => user,
                    :source => @source,
                    :url => url)
    exit if @n == 1000
  end

  def title(title)
  end

  def timestamp(timestamp)
  end

  def contributor(info)
    return nil if info[:id].blank?
    wikipedia_id = "wikipedia:#{info[:id]}"
    user = User.find_by_original_id(wikipedia_id)
    user ||= User.create(:original_id => wikipedia_id, :name => info[:name])
    user
  end

  def content(content)
  end
end

extractor = WikipediaExtractor.new(WikipediaRegister.new)
extractor.extract(ARGF)
